name: Build Eleventy

on:
  push:
    branches:
      - test-live

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependences & build
        run: |
          npm ci:
          npm run build
      
      - name: Deploy
        uses: peaceiris/actions-test-live@v3
        with:
          publish_dir: ./docs
          github_token: ${{ secrets.GITHUB_TOKEN }}